import {Geist, Geist_Mono} from "next/font/google";
import "../../globals.css";
import {ThemeProvider} from "next-themes";
import Script from "next/script";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "authentication",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <head>
            <Script async src="https://www.googletagmanager.com/gtag/js?id=G-41SGPKXLB8"></Script>
            <Script id='googletagmanager'>
                {
                    `
                    window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'G-41SGPKXLB8');
                    `
                }
            </Script>
            <title></title>
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
                {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
