import {Geist, Geist_Mono} from "next/font/google";
import "./admin.css";
import {ThemeProvider} from "next-themes";
import {ModeToggle} from "@/components/DarkModeToggle";
import {SidebarInset, SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/app-sidebar";
import {SiteHeader} from "@/components/site-header";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "admin-panel",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    let dataLayer;
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <SidebarProvider
            style={
                {
                    "--sidebar-width": "calc(var(--spacing) * 72)",
                    "--header-height": "calc(var(--spacing) * 12)"
                }
            }>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <AppSidebar variant="inset" />
            <SidebarInset >
                <SiteHeader />
                <div className="flex flex-1 flex-col">
                    <div className="@container/main flex flex-1 flex-col gap-2">
                    {children}
                </div>
                </div>
            </SidebarInset>

            {/* Mode Toggle - Desktop: bottom right next to AI chat, Mobile: top right next to burger menu */}
                <div className="fixed md:bottom-6 md:right-24 top-4 right-18 md:top-auto md:left-auto z-20">
                    <div className="w-10 h-10 md:w-12 md:h-12">
                        <ModeToggle/>
                    </div>
                </div>
        </ThemeProvider>
        </SidebarProvider>
        </body>
        </html>
    );
}
