import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import {ThemeProvider} from "next-themes";
import {ModeToggle} from "@/components/DarkModeToggle";
import {FloatingDock} from "@/components/floatingDock";
import {SidebarInset, SidebarProvider} from "@/components/ui/sidebar";
import { GoogleAnalytics } from "nextjs-google-analytics";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider>
                <SidebarInset>{children}</SidebarInset>
                <FloatingDock/>
                {/* Mode Toggle - Desktop: bottom right next to AI chat, Mobile: top right next to burger menu */}
                <div className="fixed md:bottom-6 md:right-24 top-4 right-18 md:top-auto md:left-auto z-20">
                    <div className="w-10 h-10 md:w-12 md:h-12">
                        <ModeToggle/>
                    </div>
                </div>
            </SidebarProvider>
        </ThemeProvider>
        </body>
        <GoogleAnalytics gaId="G-41SGPKXLB8"/>
        </html>
    );
}
